import {createRequire} from 'node:module'
import {mkdir} from 'node:fs/promises'
const require=createRequire(new URL('../frontend/package.json',import.meta.url))
const {chromium,firefox,expect}=require(process.env.PLAYWRIGHT_MODULE || '@playwright/test')
const base=process.env.EASYSTOCK_URL || 'http://127.0.0.1:5000'
const screenshots=new URL('../docs/screenshots/',import.meta.url).pathname
await mkdir(screenshots,{recursive:true})
const results=[]
for(const [name,engine] of [['Chromium',chromium],['Firefox',firefox]].filter(([name])=>!process.env.BROWSERS||process.env.BROWSERS.split(',').includes(name))) {
  let browser
  try {
    browser=await engine.launch({headless:true,...(name==='Chromium'&&process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage',...(process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):[])]}: {})})
    const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'uk-UA',timezoneId:'Europe/Kyiv'})
    const page=await context.newPage(), errors=[]
    const productName=`E2E ${name} ${Date.now()}`
    page.on('pageerror',e=>errors.push(e.message))
    await page.goto(base)
    await expect(page.getByRole('heading',{name:'Раді бачити вас'})).toBeVisible()
    if(name==='Chromium') await page.screenshot({path:screenshots+'01-login.png',fullPage:true})
    await page.getByRole('button',{name:'Адміністратор',exact:true}).click()
    await page.getByRole('button',{name:'Увійти в систему'}).click()
    await expect(page.getByRole('heading',{name:'Огляд складу',exact:true})).toBeVisible()
    await expect(page.getByRole('heading',{name:'Останні операції'})).toBeVisible()
    if(name==='Chromium') await page.screenshot({path:screenshots+'02-dashboard.png',fullPage:true})
    await page.getByRole('link',{name:'Товари',exact:true}).click()
    await expect(page.getByRole('button',{name:'SSD Kingston A400 480 GB',exact:true})).toBeVisible()
    if(name==='Chromium') await page.screenshot({path:screenshots+'03-products.png',fullPage:true})
    await page.getByRole('textbox',{name:'Пошук товарів'}).fill('КЛАВІАТУРА')
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await expect(page.getByRole('button',{name:'Клавіатура Logitech K120',exact:true})).toBeVisible()
    await page.getByRole('textbox',{name:'Пошук товарів'}).fill('NO-SUCH-PRODUCT')
    await expect(page.getByRole('heading',{name:'Нічого не знайдено'})).toBeVisible()
    await page.getByRole('button',{name:'Очистити фільтри',exact:true}).click()
    // Exercise real UI CRUD, then the exact acceptance scenario on a fresh product.
    await page.getByRole('button',{name:'Додати товар',exact:true}).click()
    const dialog=page.getByRole('dialog')
    await dialog.getByLabel('Назва / ім’я').fill(productName)
    await dialog.getByLabel('Артикул (SKU)').fill(`E2E-${name.toUpperCase()}-${Date.now()}`)
    await dialog.getByLabel('Ціна, грн').fill('1450')
    await dialog.getByRole('button',{name:'Зберегти',exact:true}).click()
    await expect(dialog).toHaveCount(0)
    await page.getByRole('button',{name:productName,exact:true}).click()
    await expect(page.getByRole('heading',{name:productName,exact:true})).toBeVisible()
    const id=page.url().split('/').at(-1)
    async function receive(quantity) {
      await page.getByRole('button',{name:'Надходження',exact:true}).click()
      await expect(page.getByRole('heading',{name:'Нове надходження',exact:true})).toBeVisible()
      await page.getByRole('spinbutton',{name:'Кількість 1'}).fill(String(quantity))
      await page.getByRole('button',{name:'Провести надходження',exact:true}).click()
      await expect(page.locator('.success')).toBeVisible()
      await page.getByRole('button',{name:'До товарів',exact:true}).click()
      await expect(page.locator('.stock-number')).toContainText(String(quantity===17?17:37))
    }
    await receive(17)
    if(name==='Chromium') await page.screenshot({path:screenshots+'04-product-detail.png',fullPage:true})
    await page.getByRole('button',{name:'Надходження',exact:true}).click()
    await page.getByRole('spinbutton',{name:'Кількість 1'}).fill('20')
    if(name==='Chromium') await page.screenshot({path:screenshots+'05-receipt.png',fullPage:true})
    await page.getByRole('button',{name:'Провести надходження',exact:true}).click()
    await expect(page.locator('.success')).toContainText('37')
    await page.reload()
    await expect(page.getByRole('spinbutton',{name:'Кількість 1'})).toHaveValue('')
    await page.getByRole('button',{name:'До товарів',exact:true}).click()
    await expect(page.locator('.stock-number')).toContainText('37')
    await page.getByRole('button',{name:'Списання',exact:true}).click()
    await page.getByRole('spinbutton',{name:'Кількість 1'}).fill('40')
    await page.getByRole('textbox',{name:'Причина списання / коментар'}).fill('Перевірка збереження полів після помилки')
    await page.getByRole('button',{name:'Провести списання',exact:true}).click()
    await expect(page.getByRole('alert')).toContainText('Недостатньо товару')
    await expect(page.getByRole('spinbutton',{name:'Кількість 1'})).toHaveValue('40')
    await expect(page.getByRole('textbox',{name:'Причина списання / коментар'})).toHaveValue('Перевірка збереження полів після помилки')
    await expect(page.locator('.balance-hint')).toContainText('37')
    if(name==='Chromium') await page.screenshot({path:screenshots+'06-writeoff-error.png',fullPage:true})
    await page.getByRole('spinbutton',{name:'Кількість 1'}).fill('37')
    await page.getByRole('button',{name:'Провести списання',exact:true}).click()
    await expect(page.locator('.success')).toContainText('новий залишок 0')
    await page.getByRole('button',{name:'Перейти до історії',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Історія операцій',exact:true})).toBeVisible()
    await expect(page.locator('tbody tr').first()).toContainText(productName)
    if(name==='Chromium') await page.screenshot({path:screenshots+'07-history.png',fullPage:true})
    await page.goto(base+'/#products/'+id)
    await page.getByRole('button',{name:'Архівувати товар',exact:true}).click()
    await page.getByRole('dialog').getByRole('button',{name:'Архівувати',exact:true}).click()
    await expect(page.getByText('Товар архівовано. Історія операцій збережена.',{exact:true})).toBeVisible()
    await page.getByRole('link',{name:'Користувачі',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Користувачі',exact:true})).toBeVisible()
    if(name==='Chromium') await page.screenshot({path:screenshots+'08-users.png',fullPage:true})
    await page.getByRole('button',{name:'Вийти із системи'}).click()
    await page.getByRole('button',{name:'Менеджер',exact:true}).click()
    await page.getByRole('button',{name:'Увійти в систему'}).click()
    await expect(page.getByRole('heading',{name:'Огляд складу',exact:true})).toBeVisible()
    await expect(page.getByRole('link',{name:'Надходження',exact:true})).toHaveCount(0)
    await expect(page.getByRole('link',{name:'Користувачі',exact:true})).toHaveCount(0)
    await page.goto(base+'/#receipt')
    await expect(page.getByRole('heading',{name:'Доступ обмежено'})).toBeVisible()
    if(name==='Chromium') {
      await page.goto(base+'/#dashboard')
      await page.setViewportSize({width:390,height:844})
      await expect(page.getByRole('heading',{name:'Огляд складу',exact:true})).toBeVisible()
      await page.screenshot({path:screenshots+'09-mobile.png',fullPage:true})
      const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)
      if(overflow) throw Error('Mobile page overflows viewport')
      await page.getByRole('button',{name:'Відкрити меню'}).click()
      await page.getByRole('link',{name:'Товари',exact:true}).click()
      await expect(page.getByRole('heading',{name:'Товари',exact:true})).toBeVisible()
    }
    if(errors.length) throw Error(errors.join('\n'))
    results.push(name+': PASS — login, search, empty state, product CRUD, +20, persistence, excess writeoff, preserved inputs, history, archive, roles'+(name==='Chromium'?', mobile':''))
  } catch(error) {
    results.push(name+': FAIL — '+error.stack)
    process.exitCode=1
  } finally {await browser?.close()}
}
console.log(results.join('\n'))
